version: "3.9"
services:
  uaa:
    image: hortonworks/cloudbreak-uaa:3.6.3
    ports:
      - "8080:8080"
    environment:
      - UAA_CONFIG_URL=https://raw.githubusercontent.com/elisoncrum/is-it-down/master/uaa.yml
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=testing
      - MYSQL_USER=testing
      - MYSQL_PASSWORD=testing
      - MYSQL_ROOT_PASSWORD=testing
  worker:
    build:
      context: .
      dockerfile: worker/worker.Dockerfile
      args:
        buildno: 1
    links:
      - "db:database"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=database
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
      args:
        buildno: 1
    links:
      - "db:database"
      - "uaa:uaa"
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABSE_HOST=database